# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-17 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageUploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ['-uploadTime']},
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
